# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d44932a3cbdcf9916d944bd5f16cea124898206cd4db62c2bb6e89fb81aa9b86562177c70f0ed3a3efe10cfdc7f3024ff04958c0dc9da98a8d8d9794a94e989e

test:
  secret_key_base: 5d1176914bea93aa508a39a6beafbc21a2d5343ae4cb05b3122af222cfc429e6f66e3aff5f23d128ac805f77636fa458beb53077a43269da977500271bbd71ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
